import {
  ExecutionStatus,
  type AppState,
  type CheckResult,
  type CheckType,
  type Evidence,
  type FailureSeverity,
  type Notification,
  type TemplateCategory,
  type TemplateCheck,
} from "@/types/domain";

const now = Date.UTC(2026, 7, 12, 9, 0, 0);
const iso = (offsetHours: number) => new Date(now + offsetHours * 3600_000).toISOString();

const TEMPLATE_ID = "tpl-ojas-eqt-r3";

interface CheckSeed {
  code: string;
  title: string;
  description: string;
  instruction: string;
  expectedResult: string;
  acceptanceCriteria: string;
  testType: CheckType;
  mandatory?: boolean;
  allowNA?: boolean;
  evidenceRequired?: boolean;
  measurementUnit?: string | null;
  measurementMin?: number | null;
  measurementMax?: number | null;
  defaultFailureCategory?: string | null;
}

interface CategorySeed {
  name: string;
  checks: CheckSeed[];
}

const CATEGORY_SEEDS: CategorySeed[] = [
  {
    name: "Check-in",
    checks: [
      {
        code: "CHK-001",
        title: "Unit Receipt Visual Inspection",
        description:
          "Confirm the unit arrives free of visible transport damage before testing begins.",
        instruction: "Inspect the chassis, screen and ports for cracks, dents or moisture ingress.",
        expectedResult: "No visible damage; unit matches the expected model and colour variant.",
        acceptanceCriteria: "Zero visible defects on chassis, display or ports.",
        testType: "visual",
        mandatory: true,
        evidenceRequired: true,
        defaultFailureCategory: "Mechanical",
      },
      {
        code: "CHK-002",
        title: "USN Label Verification",
        description: "Verify the physical USN label matches the unit record in the system.",
        instruction: "Scan or read the USN label and compare it against the assignment record.",
        expectedResult: "USN label matches the assigned unit exactly.",
        acceptanceCriteria: "Exact match, no illegible characters.",
        testType: "binary",
        mandatory: true,
        defaultFailureCategory: "Other",
      },
    ],
  },
  {
    name: "Activation",
    checks: [
      {
        code: "ACT-001",
        title: "Power-On Verification",
        description: "Verify the unit powers on and reaches the boot logo within spec.",
        instruction: "Hold the power button for 3 seconds and observe the boot sequence.",
        expectedResult: "Boot logo appears within 5 seconds; no unexpected reboot loop.",
        acceptanceCriteria: "Boot logo within 5 s, stable power-on.",
        testType: "binary",
        mandatory: true,
        defaultFailureCategory: "Electrical",
      },
      {
        code: "ACT-002",
        title: "OS Boot & Activation",
        description: "Verify the unit completes OS boot and activation handshake.",
        instruction: "Allow the unit to complete first-boot setup and confirm activation status.",
        expectedResult: "OS reaches home screen; activation status reports ACTIVATED.",
        acceptanceCriteria: "Activation status ACTIVATED within 90 seconds of boot.",
        testType: "binary",
        mandatory: true,
        defaultFailureCategory: "Software",
      },
    ],
  },
  {
    name: "Acoustics",
    checks: [
      {
        code: "ACO-001",
        title: "Speaker Continuity Check",
        description: "Verify both speaker channels produce audible output.",
        instruction: "Play the reference test tone and confirm output from both channels.",
        expectedResult: "Audible, clear output from both left and right channels.",
        acceptanceCriteria: "No channel dropout, no audible distortion.",
        testType: "binary",
        mandatory: true,
        defaultFailureCategory: "Acoustic",
      },
      {
        code: "ACO-002",
        title: "Speaker Output Level",
        description: "Measure peak speaker output level against the reference tone.",
        instruction:
          "Position the calibrated SPL meter 30 cm from the speaker grille and record the peak level.",
        expectedResult: "Peak output between 60 dB and 90 dB.",
        acceptanceCriteria: "60 dB ≤ measured level ≤ 90 dB.",
        testType: "measurement",
        mandatory: true,
        measurementUnit: "dB",
        measurementMin: 60,
        measurementMax: 90,
        defaultFailureCategory: "Acoustic",
      },
      {
        code: "ACO-003",
        title: "Microphone Pickup Test",
        description: "Verify the microphone captures a clean recording during the voice test.",
        instruction: "Record 5 seconds of the reference phrase and play it back for clarity.",
        expectedResult: "Playback is clear with no clipping or excessive noise floor.",
        acceptanceCriteria: "Clear, intelligible playback.",
        testType: "ternary",
        allowNA: true,
        defaultFailureCategory: "Acoustic",
      },
    ],
  },
  {
    name: "Camera",
    checks: [
      {
        code: "CAM-001",
        title: "Rear Camera Image Quality",
        description: "Capture a reference chart image and verify focus, colour and exposure.",
        instruction: "Capture the calibration chart under standard lab lighting.",
        expectedResult: "Sharp focus, accurate colour reproduction, no visible artefacts.",
        acceptanceCriteria: "No blur, banding or colour cast on the calibration chart.",
        testType: "visual",
        mandatory: true,
        evidenceRequired: true,
        defaultFailureCategory: "Visual",
      },
      {
        code: "CAM-002",
        title: "Front Camera Functional Test",
        description: "Verify the front camera activates and streams a live preview.",
        instruction: "Open the camera app in selfie mode and confirm a live preview renders.",
        expectedResult: "Live preview renders within 2 seconds, no artefacts.",
        acceptanceCriteria: "Preview latency under 2 s.",
        testType: "binary",
        mandatory: true,
        defaultFailureCategory: "Software",
      },
      {
        code: "CAM-003",
        title: "Autofocus Response",
        description: "Verify autofocus locks correctly across near and far reference targets.",
        instruction: "Tap-to-focus on the near target, then the far target, and observe lock time.",
        expectedResult: "Focus lock achieved within 1 second for both targets.",
        acceptanceCriteria: "Focus lock ≤ 1 s, no hunting.",
        testType: "binary",
        mandatory: true,
        defaultFailureCategory: "Functional",
      },
      {
        code: "CAM-004",
        title: "Flash / Strobe Test",
        description: "Verify the camera flash fires correctly in low-light capture.",
        instruction: "Capture an image in the darkened booth with flash enabled.",
        expectedResult: "Flash fires and produces adequately lit exposure.",
        acceptanceCriteria: "Correct exposure, no flash failure.",
        testType: "ternary",
        allowNA: true,
        defaultFailureCategory: "Electrical",
      },
    ],
  },
  {
    name: "Battery",
    checks: [
      {
        code: "BAT-001",
        title: "Charge Cycle Verification",
        description: "Verify the unit accepts charge and reports charging status correctly.",
        instruction: "Connect the reference charger and confirm the charging indicator activates.",
        expectedResult: "Charging indicator activates within 5 seconds of connection.",
        acceptanceCriteria: "Indicator active, charge current within spec.",
        testType: "binary",
        mandatory: true,
        defaultFailureCategory: "Electrical",
      },
      {
        code: "BAT-002",
        title: "Battery Voltage Measurement",
        description: "Measure resting battery voltage after the standard conditioning cycle.",
        instruction: "Measure terminal voltage with the calibrated multimeter after conditioning.",
        expectedResult: "Voltage between 3.70 V and 4.35 V.",
        acceptanceCriteria: "3.70 V ≤ measured voltage ≤ 4.35 V.",
        testType: "measurement",
        mandatory: true,
        measurementUnit: "V",
        measurementMin: 3.7,
        measurementMax: 4.35,
        defaultFailureCategory: "Electrical",
      },
    ],
  },
  {
    name: "Connectivity",
    checks: [
      {
        code: "CON-001",
        title: "Wi-Fi Association Test",
        description: "Verify the unit associates with the reference access point.",
        instruction: "Connect to the lab reference SSID and confirm IP address assignment.",
        expectedResult: "Associates and receives a valid IP address within 10 seconds.",
        acceptanceCriteria: "Association ≤ 10 s, stable signal.",
        testType: "binary",
        mandatory: true,
        defaultFailureCategory: "Connectivity",
      },
      {
        code: "CON-002",
        title: "Bluetooth Pairing Test",
        description: "Verify Bluetooth pairing with the reference accessory.",
        instruction:
          "Pair with the reference Bluetooth headset and confirm audio routes correctly.",
        expectedResult: "Pairs within 15 seconds; audio routes to the accessory.",
        acceptanceCriteria: "Pairing ≤ 15 s, stable connection.",
        testType: "binary",
        defaultFailureCategory: "Connectivity",
      },
    ],
  },
  {
    name: "Shipping",
    checks: [
      {
        code: "SHP-001",
        title: "Packaging Integrity Check",
        description: "Verify retail packaging is undamaged and seals are intact.",
        instruction: "Inspect the retail box, foam insert and tamper-evident seals.",
        expectedResult: "No visible damage; seals intact.",
        acceptanceCriteria: "Intact seals, no crushed corners.",
        testType: "visual",
        evidenceRequired: true,
        defaultFailureCategory: "Mechanical",
      },
      {
        code: "SHP-002",
        title: "Accessory Completeness Check",
        description: "Verify all listed accessories are present in the box.",
        instruction: "Check off each accessory against the bill of materials.",
        expectedResult: "All listed accessories present.",
        acceptanceCriteria: "100% of BOM accessories present.",
        testType: "ternary",
        allowNA: true,
        defaultFailureCategory: "Other",
      },
    ],
  },
];

function buildCategoriesAndChecks(): { categories: TemplateCategory[]; checks: TemplateCheck[] } {
  const categories: TemplateCategory[] = [];
  const checks: TemplateCheck[] = [];
  let sequence = 1;
  CATEGORY_SEEDS.forEach((cat, catIndex) => {
    const categoryId = `cat-${cat.name.toLowerCase().replace(/[^a-z]+/g, "-")}`;
    categories.push({
      id: categoryId,
      templateId: TEMPLATE_ID,
      name: cat.name,
      sequence: catIndex + 1,
    });
    for (const c of cat.checks) {
      checks.push({
        id: `chk-${c.code.toLowerCase()}`,
        templateId: TEMPLATE_ID,
        categoryId,
        sequence: sequence++,
        checkCode: c.code,
        title: c.title,
        description: c.description,
        instruction: c.instruction,
        expectedResult: c.expectedResult,
        acceptanceCriteria: c.acceptanceCriteria,
        testType: c.testType,
        mandatory: c.mandatory ?? false,
        allowNA: c.allowNA ?? false,
        evidenceRequired: c.evidenceRequired ?? false,
        measurementUnit: c.measurementUnit ?? null,
        measurementMin: c.measurementMin ?? null,
        measurementMax: c.measurementMax ?? null,
        defaultFailureCategory: c.defaultFailureCategory ?? null,
      });
    }
  });
  return { categories, checks };
}

const { categories: templateCategories, checks: templateChecks } = buildCategoriesAndChecks();

function checkId(code: string) {
  const found = templateChecks.find((c) => c.checkCode === code);
  if (!found) throw new Error(`Unknown seed check code: ${code}`);
  return found.id;
}

const pixel =
  "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMjAiIGhlaWdodD0iMTgwIj48cmVjdCB3aWR0aD0iMzIwIiBoZWlnaHQ9IjE4MCIgZmlsbD0iIzE2MWExZiIvPjx0ZXh0IHg9IjE2MCIgeT0iOTUiIGZpbGw9IiNmZmIzMzMiIGZvbnQtZmFtaWx5PSJtb25vc3BhY2UiIGZvbnQtc2l6ZT0iMTgiIHRleHQtYW5jaG9yPSJtaWRkbGUiPmNhcHR1cmUucG5nPC90ZXh0Pjwvc3ZnPg==";

function evidenceItem(input: {
  id: string;
  executionId: string;
  templateCheckId: string;
  attempt: number;
  filename: string;
  capturedAt: string;
}): Evidence {
  return {
    ...input,
    mimeType: "image/svg+xml",
    size: 184320,
    dataUrl: pixel,
    capturedById: "u-priya",
  };
}

function results(executionId: string, entries: Partial<CheckResult>[]): CheckResult[] {
  return entries.map((e, i) => ({
    id: `${executionId}-cr${i + 1}`,
    executionId,
    templateCheckId: "",
    attempt: 1,
    status: "not_started",
    actualResult: "",
    measurementValue: null,
    failureCategory: null,
    failureSeverity: null,
    failureDescription: "",
    testerNotes: "",
    reviewerNotes: "",
    retestReason: null,
    testerId: "u-priya",
    completedAt: null,
    updatedAt: null,
    ...e,
  }));
}

const notifications: Notification[] = [
  {
    id: "n-1",
    userId: "u-priya",
    title: "Retest required",
    body: "Rajesh Kumar requested a retest on 1 check(s) for EX-1043 (OJAS-00453).",
    href: "/executions/exec-3",
    read: false,
    createdAt: iso(-20),
  },
  {
    id: "n-2",
    userId: "u-priya",
    title: "New unit assigned",
    body: "OJAS-00451 (OJAS EQT Functional Test Rev 3) is assigned to you at EQT-01.",
    href: "/my-tests",
    read: false,
    createdAt: iso(-72),
  },
  {
    id: "n-3",
    userId: "u-rajesh",
    title: "Execution submitted for verification",
    body: "EX-1044 (OJAS-00454) submitted by Priya Sharma.",
    href: "/reviews/exec-4",
    read: false,
    createdAt: iso(-7),
  },
];

export function createSeedState(): AppState {
  return {
    session: null,
    pendingLoginUserId: null,
    failureCategories: [
      "Functional",
      "Mechanical",
      "Electrical",
      "Software",
      "Visual",
      "Performance",
      "Connectivity",
      "Acoustic",
      "Safety",
      "Other",
    ],
    users: [
      {
        id: "u-priya",
        employeeId: "TE-1001",
        name: "Priya Sharma",
        email: "priya.sharma@pibythree.example",
        role: "tester",
        active: true,
        plantIds: ["p-hosur"],
      },
      {
        id: "u-vikram",
        employeeId: "TE-1002",
        name: "Vikram Iyer",
        email: "vikram.iyer@pibythree.example",
        role: "tester",
        active: true,
        plantIds: ["p-hosur"],
      },
      {
        id: "u-meera",
        employeeId: "TE-1003",
        name: "Meera Nair",
        email: "meera.nair@pibythree.example",
        role: "tester",
        active: false,
        plantIds: ["p-hosur"],
      },
      {
        id: "u-rajesh",
        employeeId: "TE-2001",
        name: "Rajesh Kumar",
        email: "rajesh.kumar@pibythree.example",
        role: "quality_checker",
        active: true,
        plantIds: ["p-hosur"],
      },
      {
        id: "u-anita",
        employeeId: "TE-3001",
        name: "Anita Desai",
        email: "anita.desai@pibythree.example",
        role: "manager",
        active: true,
        plantIds: ["p-hosur"],
      },
      {
        id: "u-arjun",
        employeeId: "TE-4001",
        name: "Arjun Nair",
        email: "arjun.nair@pibythree.example",
        role: "senior_manager",
        active: true,
        plantIds: ["p-hosur"],
      },
      {
        id: "u-kavya",
        employeeId: "TE-5001",
        name: "Kavya Menon",
        email: "kavya.menon@pibythree.example",
        role: "template_manager",
        active: true,
        plantIds: ["p-hosur"],
      },
      {
        id: "u-admin",
        employeeId: "TE-9001",
        name: "Admin User",
        email: "platform.admin@pibythree.example",
        role: "admin",
        active: true,
        plantIds: ["p-hosur"],
      },
    ],
    plants: [{ id: "p-hosur", code: "HOS", name: "Hosur" }],
    locations: [
      { id: "loc-eqt-line", plantId: "p-hosur", name: "Building A — EQT Line" },
      { id: "loc-lab", plantId: "p-hosur", name: "Building B — Acoustics & Camera Lab" },
    ],
    stations: [
      {
        id: "sta-eqt-01",
        plantId: "p-hosur",
        locationId: "loc-eqt-line",
        code: "EQT-01",
        name: "EQT Station 1",
        status: "active",
      },
      {
        id: "sta-eqt-02",
        plantId: "p-hosur",
        locationId: "loc-eqt-line",
        code: "EQT-02",
        name: "EQT Station 2",
        status: "active",
      },
      {
        id: "sta-eqt-03",
        plantId: "p-hosur",
        locationId: "loc-lab",
        code: "EQT-03",
        name: "EQT Station 3",
        status: "active",
      },
      {
        id: "sta-eqt-04",
        plantId: "p-hosur",
        locationId: "loc-lab",
        code: "EQT-04",
        name: "EQT Station 4",
        status: "maintenance",
      },
    ],
    devices: [
      {
        id: "dev-01",
        stationId: "sta-eqt-01",
        name: "TAB-EQT-01-01",
        status: "online",
        lastSeenAt: iso(-0.1),
        assignedTesterId: "u-priya",
      },
      {
        id: "dev-02",
        stationId: "sta-eqt-02",
        name: "TAB-EQT-02-01",
        status: "online",
        lastSeenAt: iso(-0.2),
        assignedTesterId: "u-priya",
      },
      {
        id: "dev-03",
        stationId: "sta-eqt-03",
        name: "TAB-EQT-03-01",
        status: "online",
        lastSeenAt: iso(-0.5),
        assignedTesterId: "u-vikram",
      },
      {
        id: "dev-04",
        stationId: "sta-eqt-04",
        name: "TAB-EQT-04-01",
        status: "offline",
        lastSeenAt: iso(-30),
        assignedTesterId: null,
      },
    ],
    templates: [
      {
        id: TEMPLATE_ID,
        familyCode: "OJAS-EQT",
        name: "OJAS EQT Functional Test",
        revision: 3,
        status: "published",
        createdById: "u-kavya",
        createdAt: iso(-400),
        updatedById: "u-kavya",
        updatedAt: iso(-350),
        approvedById: "u-kavya",
        publishedAt: iso(-350),
        totalChecks: templateChecks.length,
        mandatoryChecks: templateChecks.filter((c) => c.mandatory).length,
      },
    ],
    templateCategories,
    templateChecks,
    units: [
      { id: "unit-451", usn: "USN-OJAS-000451", familyCode: "OJAS-EQT", createdAt: iso(-100) },
      { id: "unit-452", usn: "USN-OJAS-000452", familyCode: "OJAS-EQT", createdAt: iso(-100) },
      { id: "unit-453", usn: "USN-OJAS-000453", familyCode: "OJAS-EQT", createdAt: iso(-100) },
      { id: "unit-454", usn: "USN-OJAS-000454", familyCode: "OJAS-EQT", createdAt: iso(-100) },
      { id: "unit-455", usn: "USN-OJAS-000455", familyCode: "OJAS-EQT", createdAt: iso(-160) },
      { id: "unit-456", usn: "USN-OJAS-000456", familyCode: "OJAS-EQT", createdAt: iso(-100) },
    ],
    assignments: [
      {
        id: "as-1",
        unitId: "unit-451",
        templateId: TEMPLATE_ID,
        testerId: "u-priya",
        stationId: "sta-eqt-01",
        priority: "critical",
        dueAt: iso(48),
        assignedById: "u-anita",
        assignedAt: iso(-72),
      },
      {
        id: "as-2",
        unitId: "unit-452",
        templateId: TEMPLATE_ID,
        testerId: "u-priya",
        stationId: "sta-eqt-01",
        priority: "critical",
        dueAt: iso(24),
        assignedById: "u-anita",
        assignedAt: iso(-96),
      },
      {
        id: "as-3",
        unitId: "unit-453",
        templateId: TEMPLATE_ID,
        testerId: "u-priya",
        stationId: "sta-eqt-02",
        priority: "high",
        dueAt: iso(12),
        assignedById: "u-anita",
        assignedAt: iso(-120),
      },
      {
        id: "as-4",
        unitId: "unit-454",
        templateId: TEMPLATE_ID,
        testerId: "u-priya",
        stationId: "sta-eqt-01",
        priority: "high",
        dueAt: iso(36),
        assignedById: "u-anita",
        assignedAt: iso(-30),
      },
      {
        id: "as-5",
        unitId: "unit-455",
        templateId: TEMPLATE_ID,
        testerId: "u-vikram",
        stationId: "sta-eqt-03",
        priority: "medium",
        dueAt: iso(60),
        assignedById: "u-anita",
        assignedAt: iso(-160),
      },
      {
        id: "as-6",
        unitId: "unit-456",
        templateId: TEMPLATE_ID,
        testerId: "u-vikram",
        stationId: "sta-eqt-04",
        priority: "medium",
        dueAt: iso(72),
        assignedById: "u-anita",
        assignedAt: iso(-14),
      },
    ],
    executions: [
      {
        id: "exec-1",
        code: "EX-1041",
        assignmentId: "as-1",
        unitId: "unit-451",
        templateId: TEMPLATE_ID,
        testerId: "u-priya",
        stationId: "sta-eqt-01",
        status: ExecutionStatus.ASSIGNED,
        locationVerifiedAt: null,
        stationVerifiedAt: null,
        startedAt: null,
        submittedAt: null,
        completedAt: null,
        updatedAt: iso(-72),
        summary: "",
        round: 1,
      },
      {
        id: "exec-2",
        code: "EX-1042",
        assignmentId: "as-2",
        unitId: "unit-452",
        templateId: TEMPLATE_ID,
        testerId: "u-priya",
        stationId: "sta-eqt-01",
        status: ExecutionStatus.IN_PROGRESS,
        locationVerifiedAt: iso(-26),
        stationVerifiedAt: iso(-26),
        startedAt: iso(-26),
        submittedAt: null,
        completedAt: null,
        updatedAt: iso(-20),
        summary: "",
        round: 1,
      },
      {
        id: "exec-3",
        code: "EX-1043",
        assignmentId: "as-3",
        unitId: "unit-453",
        templateId: TEMPLATE_ID,
        testerId: "u-priya",
        stationId: "sta-eqt-02",
        status: ExecutionStatus.RETEST_REQUIRED,
        locationVerifiedAt: iso(-60),
        stationVerifiedAt: iso(-60),
        startedAt: iso(-60),
        submittedAt: iso(-46),
        completedAt: null,
        updatedAt: iso(-20),
        summary: "Speaker output measured outside the acceptance range on first pass.",
        round: 1,
      },
      {
        id: "exec-4",
        code: "EX-1044",
        assignmentId: "as-4",
        unitId: "unit-454",
        templateId: TEMPLATE_ID,
        testerId: "u-priya",
        stationId: "sta-eqt-01",
        status: ExecutionStatus.PENDING_REVIEW,
        locationVerifiedAt: iso(-12),
        stationVerifiedAt: iso(-12),
        startedAt: iso(-12),
        submittedAt: iso(-7),
        completedAt: null,
        updatedAt: iso(-7),
        summary: "Flash test marginal under low light; documented with evidence.",
        round: 1,
      },
      {
        id: "exec-5",
        code: "EX-1045",
        assignmentId: "as-5",
        unitId: "unit-455",
        templateId: TEMPLATE_ID,
        testerId: "u-vikram",
        stationId: "sta-eqt-03",
        status: ExecutionStatus.COMPLETED,
        locationVerifiedAt: iso(-160),
        stationVerifiedAt: iso(-160),
        startedAt: iso(-160),
        submittedAt: iso(-150),
        completedAt: iso(-140),
        updatedAt: iso(-140),
        summary: "All checks passed on OJAS-00455.",
        round: 1,
      },
      {
        id: "exec-6",
        code: "EX-1046",
        assignmentId: "as-6",
        unitId: "unit-456",
        templateId: TEMPLATE_ID,
        testerId: "u-vikram",
        stationId: "sta-eqt-04",
        status: ExecutionStatus.REJECTED,
        locationVerifiedAt: iso(-10),
        stationVerifiedAt: iso(-10),
        startedAt: iso(-10),
        submittedAt: iso(-9),
        completedAt: null,
        updatedAt: iso(-8),
        summary: "Multiple mandatory checks incomplete on submission.",
        round: 1,
      },
    ],
    checkResults: [
      ...results("exec-2", [
        {
          templateCheckId: checkId("CHK-001"),
          status: "passed",
          actualResult: "No visible transport damage.",
          completedAt: iso(-25),
          updatedAt: iso(-25),
        },
        {
          templateCheckId: checkId("CHK-002"),
          status: "passed",
          actualResult: "USN label matches assignment record.",
          completedAt: iso(-25),
          updatedAt: iso(-25),
        },
        {
          templateCheckId: checkId("ACT-001"),
          status: "passed",
          actualResult: "Boot logo at 2.1 s.",
          completedAt: iso(-24),
          updatedAt: iso(-24),
        },
        { templateCheckId: checkId("ACT-002"), status: "in_progress", updatedAt: iso(-20) },
      ]),
      ...results("exec-3", [
        {
          templateCheckId: checkId("CHK-001"),
          status: "passed",
          actualResult: "No visible transport damage.",
          completedAt: iso(-59),
          updatedAt: iso(-59),
        },
        {
          templateCheckId: checkId("CHK-002"),
          status: "passed",
          actualResult: "USN label matches.",
          completedAt: iso(-59),
          updatedAt: iso(-59),
        },
        {
          templateCheckId: checkId("ACT-001"),
          status: "passed",
          actualResult: "Boot logo at 1.8 s.",
          completedAt: iso(-58),
          updatedAt: iso(-58),
        },
        {
          templateCheckId: checkId("ACT-002"),
          status: "passed",
          actualResult: "Activation status ACTIVATED at 64 s.",
          completedAt: iso(-58),
          updatedAt: iso(-58),
        },
        {
          templateCheckId: checkId("ACO-001"),
          status: "passed",
          actualResult: "Both channels audible and clear.",
          completedAt: iso(-57),
          updatedAt: iso(-57),
        },
        // ACO-002 attempt 1: failed measurement, out of range — retained forever as history.
        {
          id: "exec-3-cr-aco002-1",
          templateCheckId: checkId("ACO-002"),
          attempt: 1,
          status: "failed",
          measurementValue: 94.2,
          failureCategory: "Acoustic",
          failureSeverity: "medium" as FailureSeverity,
          failureDescription: "Peak output measured at 94.2 dB, above the 90 dB acceptance limit.",
          testerNotes: "Repeated twice with the same result on the calibrated SPL meter.",
          completedAt: iso(-50),
          updatedAt: iso(-50),
        },
        // ACO-002 attempt 2: created by requestRetest, awaiting the tester.
        {
          id: "exec-3-cr-aco002-2",
          templateCheckId: checkId("ACO-002"),
          attempt: 2,
          status: "retest_required",
          reviewerNotes:
            "Re-measure with the reference SPL meter and confirm calibration certificate is current.",
          retestReason:
            "Re-measure with the reference SPL meter and confirm calibration certificate is current.",
          updatedAt: iso(-20),
        },
        {
          templateCheckId: checkId("ACO-003"),
          status: "passed",
          actualResult: "Clear playback, no clipping.",
          completedAt: iso(-56),
          updatedAt: iso(-56),
        },
      ]),
      ...results("exec-4", [
        {
          templateCheckId: checkId("CHK-001"),
          status: "passed",
          actualResult: "No visible transport damage.",
          completedAt: iso(-11),
          updatedAt: iso(-11),
        },
        {
          templateCheckId: checkId("CHK-002"),
          status: "passed",
          actualResult: "USN label matches.",
          completedAt: iso(-11),
          updatedAt: iso(-11),
        },
        {
          templateCheckId: checkId("ACT-001"),
          status: "passed",
          actualResult: "Boot logo at 2.4 s.",
          completedAt: iso(-11),
          updatedAt: iso(-11),
        },
        {
          templateCheckId: checkId("ACT-002"),
          status: "passed",
          actualResult: "Activation status ACTIVATED at 71 s.",
          completedAt: iso(-10),
          updatedAt: iso(-10),
        },
        {
          templateCheckId: checkId("ACO-001"),
          status: "passed",
          actualResult: "Both channels audible and clear.",
          completedAt: iso(-10),
          updatedAt: iso(-10),
        },
        {
          templateCheckId: checkId("ACO-002"),
          status: "passed",
          measurementValue: 78.4,
          actualResult: "78.4 dB measured.",
          completedAt: iso(-10),
          updatedAt: iso(-10),
        },
        {
          templateCheckId: checkId("ACO-003"),
          status: "passed",
          actualResult: "Clear playback.",
          completedAt: iso(-9),
          updatedAt: iso(-9),
        },
        {
          templateCheckId: checkId("CAM-001"),
          status: "passed",
          actualResult: "Sharp focus, accurate colour.",
          completedAt: iso(-9),
          updatedAt: iso(-9),
        },
        {
          templateCheckId: checkId("CAM-002"),
          status: "passed",
          actualResult: "Preview renders at 1.1 s.",
          completedAt: iso(-9),
          updatedAt: iso(-9),
        },
        {
          templateCheckId: checkId("CAM-003"),
          status: "passed",
          actualResult: "Focus lock at 0.6 s both targets.",
          completedAt: iso(-8),
          updatedAt: iso(-8),
        },
        {
          templateCheckId: checkId("CAM-004"),
          status: "failed",
          actualResult: "Exposure noticeably underexposed in low-light booth.",
          failureCategory: "Electrical",
          failureSeverity: "low" as FailureSeverity,
          failureDescription:
            "Flash fired but exposure remained underexposed by roughly 1.5 stops versus reference.",
          testerNotes: "Retested twice with the same result; flash driver may need calibration.",
          completedAt: iso(-8),
          updatedAt: iso(-8),
        },
        {
          templateCheckId: checkId("BAT-001"),
          status: "passed",
          actualResult: "Charging indicator active at 3 s.",
          completedAt: iso(-8),
          updatedAt: iso(-8),
        },
        {
          templateCheckId: checkId("BAT-002"),
          status: "passed",
          measurementValue: 4.01,
          actualResult: "4.01 V measured.",
          completedAt: iso(-7),
          updatedAt: iso(-7),
        },
        {
          templateCheckId: checkId("CON-001"),
          status: "passed",
          actualResult: "Associated in 4 s.",
          completedAt: iso(-7),
          updatedAt: iso(-7),
        },
        {
          templateCheckId: checkId("CON-002"),
          status: "passed",
          actualResult: "Paired in 6 s, audio routed correctly.",
          completedAt: iso(-7),
          updatedAt: iso(-7),
        },
        {
          templateCheckId: checkId("SHP-001"),
          status: "passed",
          actualResult: "Seals intact, no damage.",
          completedAt: iso(-7),
          updatedAt: iso(-7),
        },
        {
          templateCheckId: checkId("SHP-002"),
          status: "passed",
          actualResult: "All accessories present.",
          completedAt: iso(-7),
          updatedAt: iso(-7),
        },
      ]),
      ...results(
        "exec-5",
        templateChecks.map((c) => ({
          templateCheckId: c.id,
          status: "passed" as const,
          actualResult: "Within specification.",
          measurementValue:
            c.testType === "measurement"
              ? ((c.measurementMin ?? 0) + (c.measurementMax ?? 0)) / 2
              : null,
          testerId: "u-vikram",
          completedAt: iso(-150),
          updatedAt: iso(-150),
        })),
      ),
      ...results("exec-6", [
        {
          templateCheckId: checkId("CHK-001"),
          status: "passed",
          actualResult: "No visible transport damage.",
          testerId: "u-vikram",
          completedAt: iso(-9),
          updatedAt: iso(-9),
        },
        {
          templateCheckId: checkId("CHK-002"),
          status: "passed",
          actualResult: "USN label matches.",
          testerId: "u-vikram",
          completedAt: iso(-9),
          updatedAt: iso(-9),
        },
      ]),
    ],
    evidence: [
      evidenceItem({
        id: "ev-1",
        executionId: "exec-3",
        templateCheckId: checkId("ACO-002"),
        attempt: 1,
        filename: "spl-meter-reading.png",
        capturedAt: iso(-50),
      }),
      evidenceItem({
        id: "ev-2",
        executionId: "exec-4",
        templateCheckId: checkId("CAM-004"),
        attempt: 1,
        filename: "flash-exposure-capture.png",
        capturedAt: iso(-8),
      }),
      evidenceItem({
        id: "ev-3",
        executionId: "exec-4",
        templateCheckId: checkId("CAM-001"),
        attempt: 1,
        filename: "calibration-chart.png",
        capturedAt: iso(-9),
      }),
      evidenceItem({
        id: "ev-4",
        executionId: "exec-4",
        templateCheckId: checkId("CHK-001"),
        attempt: 1,
        filename: "unit-receipt.png",
        capturedAt: iso(-11),
      }),
      evidenceItem({
        id: "ev-5",
        executionId: "exec-4",
        templateCheckId: checkId("SHP-001"),
        attempt: 1,
        filename: "packaging-seals.png",
        capturedAt: iso(-7),
      }),
    ],
    reviews: [
      {
        id: "rv-1",
        executionId: "exec-3",
        reviewerId: "u-rajesh",
        decision: "retest_requested",
        comment:
          "Speaker output exceeds the acceptance range. Re-measure with the reference SPL meter and confirm calibration certificate is current.",
        affectedCheckIds: [checkId("ACO-002")],
        createdAt: iso(-20),
        round: 1,
      },
      {
        id: "rv-2",
        executionId: "exec-5",
        reviewerId: "u-rajesh",
        decision: "approved",
        comment: "All checks passed with adequate evidence. Approved for release sign-off.",
        affectedCheckIds: [],
        createdAt: iso(-140),
        round: 1,
      },
      {
        id: "rv-3",
        executionId: "exec-6",
        reviewerId: "u-rajesh",
        decision: "rejected",
        comment:
          "Only 2 of 17 checks recorded; unit was submitted prematurely. Re-run from Check-in.",
        affectedCheckIds: [],
        createdAt: iso(-8),
        round: 1,
      },
    ],
    notifications,
    audit: [
      {
        id: "au-1",
        actorId: "u-anita",
        action: "assignment.created",
        entity: "Assignment",
        entityId: "as-1",
        createdAt: iso(-72),
        metadata: { unit: "USN-OJAS-000451", tester: "Priya Sharma" },
      },
      {
        id: "au-2",
        actorId: "u-priya",
        action: "execution.submitted",
        entity: "Execution",
        entityId: "exec-3",
        createdAt: iso(-46),
        metadata: { code: "EX-1043" },
      },
      {
        id: "au-3",
        actorId: "u-rajesh",
        action: "review.retest_requested",
        entity: "Execution",
        entityId: "exec-3",
        createdAt: iso(-20),
        metadata: { code: "EX-1043", checks: 1 },
      },
      {
        id: "au-4",
        actorId: "u-priya",
        action: "execution.submitted",
        entity: "Execution",
        entityId: "exec-4",
        createdAt: iso(-7),
        metadata: { code: "EX-1044" },
      },
      {
        id: "au-5",
        actorId: "u-rajesh",
        action: "review.approved",
        entity: "Execution",
        entityId: "exec-5",
        createdAt: iso(-140),
        metadata: { code: "EX-1045" },
      },
      {
        id: "au-6",
        actorId: "u-rajesh",
        action: "review.rejected",
        entity: "Execution",
        entityId: "exec-6",
        createdAt: iso(-8),
        metadata: { code: "EX-1046" },
      },
      {
        id: "au-7",
        actorId: "u-kavya",
        action: "template.published",
        entity: "Template",
        entityId: TEMPLATE_ID,
        createdAt: iso(-350),
        metadata: { familyCode: "OJAS-EQT", revision: 3 },
      },
    ],
  };
}
