/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as MyTestsRouteImport } from './routes/my-tests'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as ExecutionsExecutionIdRouteImport } from './routes/executions.$executionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTestsRoute = MyTestsRouteImport.update({
  id: '/my-tests',
  path: '/my-tests',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutionsExecutionIdRoute = ExecutionsExecutionIdRouteImport.update({
  id: '/executions/$executionId',
  path: '/executions/$executionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/my-tests': typeof MyTestsRoute
  '/otp': typeof OtpRoute
  '/executions/$executionId': typeof ExecutionsExecutionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/my-tests': typeof MyTestsRoute
  '/otp': typeof OtpRoute
  '/executions/$executionId': typeof ExecutionsExecutionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/my-tests': typeof MyTestsRoute
  '/otp': typeof OtpRoute
  '/executions/$executionId': typeof ExecutionsExecutionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/dashboard' | '/my-tests' | '/otp' | '/executions/$executionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/my-tests' | '/otp' | '/executions/$executionId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/my-tests'
    | '/otp'
    | '/executions/$executionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  MyTestsRoute: typeof MyTestsRoute
  OtpRoute: typeof OtpRoute
  ExecutionsExecutionIdRoute: typeof ExecutionsExecutionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-tests': {
      id: '/my-tests'
      path: '/my-tests'
      fullPath: '/my-tests'
      preLoaderRoute: typeof MyTestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executions/$executionId': {
      id: '/executions/$executionId'
      path: '/executions/$executionId'
      fullPath: '/executions/$executionId'
      preLoaderRoute: typeof ExecutionsExecutionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  MyTestsRoute: MyTestsRoute,
  OtpRoute: OtpRoute,
  ExecutionsExecutionIdRoute: ExecutionsExecutionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
