/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as MyTestsRouteImport } from './routes/my-tests'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as VerifyLocationRouteImport } from './routes/verify-location'
import { Route as VerifyStationRouteImport } from './routes/verify-station'
import { Route as ExecutionsExecutionIdRouteImport } from './routes/executions.$executionId'
import { Route as ReviewsIndexRouteImport } from './routes/reviews.index'
import { Route as ReviewsExecutionIdRouteImport } from './routes/reviews.$executionId'
import { Route as TemplatesIndexRouteImport } from './routes/templates.index'
import { Route as TemplatesTemplateIdRouteImport } from './routes/templates.$templateId'
import { Route as UnitsUnitIdRouteImport } from './routes/units.$unitId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTestsRoute = MyTestsRouteImport.update({
  id: '/my-tests',
  path: '/my-tests',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyLocationRoute = VerifyLocationRouteImport.update({
  id: '/verify-location',
  path: '/verify-location',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyStationRoute = VerifyStationRouteImport.update({
  id: '/verify-station',
  path: '/verify-station',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutionsExecutionIdRoute = ExecutionsExecutionIdRouteImport.update({
  id: '/executions/$executionId',
  path: '/executions/$executionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsIndexRoute = ReviewsIndexRouteImport.update({
  id: '/reviews/',
  path: '/reviews/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsExecutionIdRoute = ReviewsExecutionIdRouteImport.update({
  id: '/reviews/$executionId',
  path: '/reviews/$executionId',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesTemplateIdRoute = TemplatesTemplateIdRouteImport.update({
  id: '/templates/$templateId',
  path: '/templates/$templateId',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitsUnitIdRoute = UnitsUnitIdRouteImport.update({
  id: '/units/$unitId',
  path: '/units/$unitId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/my-tests': typeof MyTestsRoute
  '/otp': typeof OtpRoute
  '/reports': typeof ReportsRoute
  '/verify-location': typeof VerifyLocationRoute
  '/verify-station': typeof VerifyStationRoute
  '/executions/$executionId': typeof ExecutionsExecutionIdRoute
  '/reviews/$executionId': typeof ReviewsExecutionIdRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/units/$unitId': typeof UnitsUnitIdRoute
  '/reviews/': typeof ReviewsIndexRoute
  '/templates/': typeof TemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/my-tests': typeof MyTestsRoute
  '/otp': typeof OtpRoute
  '/reports': typeof ReportsRoute
  '/verify-location': typeof VerifyLocationRoute
  '/verify-station': typeof VerifyStationRoute
  '/executions/$executionId': typeof ExecutionsExecutionIdRoute
  '/reviews/$executionId': typeof ReviewsExecutionIdRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/units/$unitId': typeof UnitsUnitIdRoute
  '/reviews': typeof ReviewsIndexRoute
  '/templates': typeof TemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/my-tests': typeof MyTestsRoute
  '/otp': typeof OtpRoute
  '/reports': typeof ReportsRoute
  '/verify-location': typeof VerifyLocationRoute
  '/verify-station': typeof VerifyStationRoute
  '/executions/$executionId': typeof ExecutionsExecutionIdRoute
  '/reviews/$executionId': typeof ReviewsExecutionIdRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/units/$unitId': typeof UnitsUnitIdRoute
  '/reviews/': typeof ReviewsIndexRoute
  '/templates/': typeof TemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/my-tests'
    | '/otp'
    | '/reports'
    | '/verify-location'
    | '/verify-station'
    | '/executions/$executionId'
    | '/reviews/$executionId'
    | '/templates/$templateId'
    | '/units/$unitId'
    | '/reviews/'
    | '/templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/my-tests'
    | '/otp'
    | '/reports'
    | '/verify-location'
    | '/verify-station'
    | '/executions/$executionId'
    | '/reviews/$executionId'
    | '/templates/$templateId'
    | '/units/$unitId'
    | '/reviews'
    | '/templates'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/my-tests'
    | '/otp'
    | '/reports'
    | '/verify-location'
    | '/verify-station'
    | '/executions/$executionId'
    | '/reviews/$executionId'
    | '/templates/$templateId'
    | '/units/$unitId'
    | '/reviews/'
    | '/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  MyTestsRoute: typeof MyTestsRoute
  OtpRoute: typeof OtpRoute
  ReportsRoute: typeof ReportsRoute
  VerifyLocationRoute: typeof VerifyLocationRoute
  VerifyStationRoute: typeof VerifyStationRoute
  ExecutionsExecutionIdRoute: typeof ExecutionsExecutionIdRoute
  ReviewsExecutionIdRoute: typeof ReviewsExecutionIdRoute
  TemplatesTemplateIdRoute: typeof TemplatesTemplateIdRoute
  UnitsUnitIdRoute: typeof UnitsUnitIdRoute
  ReviewsIndexRoute: typeof ReviewsIndexRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-tests': {
      id: '/my-tests'
      path: '/my-tests'
      fullPath: '/my-tests'
      preLoaderRoute: typeof MyTestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-location': {
      id: '/verify-location'
      path: '/verify-location'
      fullPath: '/verify-location'
      preLoaderRoute: typeof VerifyLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-station': {
      id: '/verify-station'
      path: '/verify-station'
      fullPath: '/verify-station'
      preLoaderRoute: typeof VerifyStationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executions/$executionId': {
      id: '/executions/$executionId'
      path: '/executions/$executionId'
      fullPath: '/executions/$executionId'
      preLoaderRoute: typeof ExecutionsExecutionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/': {
      id: '/reviews/'
      path: '/reviews'
      fullPath: '/reviews/'
      preLoaderRoute: typeof ReviewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/$executionId': {
      id: '/reviews/$executionId'
      path: '/reviews/$executionId'
      fullPath: '/reviews/$executionId'
      preLoaderRoute: typeof ReviewsExecutionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$templateId': {
      id: '/templates/$templateId'
      path: '/templates/$templateId'
      fullPath: '/templates/$templateId'
      preLoaderRoute: typeof TemplatesTemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/units/$unitId': {
      id: '/units/$unitId'
      path: '/units/$unitId'
      fullPath: '/units/$unitId'
      preLoaderRoute: typeof UnitsUnitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  MyTestsRoute: MyTestsRoute,
  OtpRoute: OtpRoute,
  ReportsRoute: ReportsRoute,
  VerifyLocationRoute: VerifyLocationRoute,
  VerifyStationRoute: VerifyStationRoute,
  ExecutionsExecutionIdRoute: ExecutionsExecutionIdRoute,
  ReviewsExecutionIdRoute: ReviewsExecutionIdRoute,
  TemplatesTemplateIdRoute: TemplatesTemplateIdRoute,
  UnitsUnitIdRoute: UnitsUnitIdRoute,
  ReviewsIndexRoute: ReviewsIndexRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
